version: "3.9"
services:
  # 백엔드
  backend-proxy-server:
    image: ghcr.io/dev-montyoh/backend-proxy-server:latest
    container_name: backend-proxy-server
    ports:
      - "80:80"
    networks:
      backend-network:
    restart: always

  # gateway
  backend-api-server-gateway:
    image: ghcr.io/dev-montyoh/backend-api-server-gateway:latest
    container_name: backend-api-server-gateway
    ports:
      - "3000:3000"
    networks:
      backend-network:
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: prod
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}

  # content
  backend-api-server-content:
    image: ghcr.io/dev-montyoh/backend-api-server-content:latest
    container_name: backend-api-server-content
    ports:
      - "3002:3002"
    networks:
      backend-network:
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: prod
      CLOUDFLARE_ACCOUNT_ID: ${CLOUDFLARE_ACCOUNT_ID}
      CLOUDFLARE_ACCESS_KEY: ${CLOUDFLARE_ACCESS_KEY}
      CLOUDFLARE_SECRET_KEY: ${CLOUDFLARE_SECRET_KEY}
      CLOUDFLARE_R2_END_POINT: ${CLOUDFLARE_R2_END_POINT}
      CLOUDFLARE_R2_BUCKET_NAME: ${CLOUDFLARE_R2_BUCKET_NAME}

  # payment
  backend-api-server-payment:
    image: ghcr.io/dev-montyoh/backend-api-server-payment:latest
    container_name: backend-api-server-payment
    ports:
      - "3003:3003"
    networks:
      backend-network:
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      PAYMENT_INICIS_SIGN_KEY: ${PAYMENT_INICIS_SIGN_KEY}
      PAYMENT_INICIS_MID: ${PAYMENT_INICIS_MID}
      PAYMENT_INICIS_INIAPIKEY: ${PAYMENT_INICIS_INIAPIKEY}
      PAYMENT_NICEPAY_MERCHANT_KEY: ${PAYMENT_NICEPAY_MERCHANT_KEY}
      PAYMENT_NICEPAY_MID: ${PAYMENT_NICEPAY_MID}

  # 프론트
  frontend-portfolio:
    image: ghcr.io/dev-montyoh/frontend-portfolio:latest
    container_name: frontend-portfolio
    ports:
      - "8080:8080"
    networks:
      backend-network:
    restart: always

  frontend-payment:
    image: ghcr.io/dev-montyoh/frontend-payment:latest
    container_name: frontend-payment
    ports:
      - "8081:8081"
    networks:
      backend-network:
    restart: always

networks:
  backend-network:
    driver: bridge
